### ISSUE TITLE
Auto select exe folder by game name if it exists

### ISSUE THREAD

**Issue by RoxxxySin** [Willy-JL/F95Checker#102]
The "Set exe dir" folder could be searched for an executable by matching folder name against the name of the game (possibly taking the game type into account too, e.g. renpy) when the "Add Exe" button is pushed.

- If no matches were found, open "old" "Select or drop executable for ..." dialog.
- If a single match is found, show the found folder with a confirmation dialog: "Do you want to add this folder to [GAME NAME]?", "Yes/No/Manual Search". (Where "Manual Search" is the "old" dialog).
- If multiple matches is found, show a dialog with a list of the matches similar to the "RPDL" search results dialog.

I think this will save a lot of time adding games on a "game hoarders" machine (guilty as charged), when most of the time there's almost a 1-1 mapping between the game name and the game install folder.

**Comment by Willy-JL** [comment]
for now, this simply pre-selects the game folder if it exists. it expects a folder name with just letters, numbers, and spaces. "&" character is converted to "and". for example "Lorem & Ipsum - An example game" becomes "Lorem and Ipsum An example game". if this folder exists directly inside your set exe dir, then it will be shown by default.

**Comment by Willy-JL** [comment]
might expand on it in the future with showing a list of detected executables, but considering how many different kinds of executables ther could be, not fully set on it yet
