### ISSUE TITLE
Option to hide or ignore game updates for specific games

### ISSUE THREAD

**Issue by RoxxxySin** [Willy-JL/F95Checker#103]
I use the checker to keep track of all the different games I've played. From time to time I come across a game that doesn't interest me and I mark the game with a custom label ("Ignore"). Basically a reminder to myself: You tried this game and didn't find it interesting.

So when I try to add a game I've already added, I can tell whether I've played the game before. Because honestly, I play so many games that I can't remember all of them :)

This works great with the filters but I still get updates for that game, which I would prefer not to get.

Perhaps this could somehow be tied to "Personal Rating"? I.e., all 1 Star rated games is automatically "ignored" if an configuration option is enabled.

**Comment by Willy-JL** [comment]
right click > archive
