### ISSUE TITLE
Itchi.io ?

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [Willy-JL/F95Checker#105]
I follow a handful of games on itch.io which, for one reason or another, are not on F95Zone. I suppose I could add them to F95Zone, but then I'd have to maintain that page, etc, and I'm often away from the internet for weeks at a time. I also suppose I could add them as custom games in F95Checker. Hmm...

It seems like it should be fairly straightforward to scrape game pages (does itch have an API? A: Yes; limited.) and populate the F95Checker with them. Game description and download links are all in the same semantic-html places. Changelogs are a bit more awkward...

**Comment by Willy-JL** [comment]
this is exactly why i added support for custom games.
