### ISSUE TITLE
Proposal for Improving Security and Flexibility

### ISSUE THREAD

**Issue by medzhidov** [Willy-JL/F95Checker#108]
Hello!

I would like to suggest an enhancement that will improve the security of game launches and provide users with more flexibility in managing this process.

Sandboxie Integration:
I propose adding integration with the Sandboxie program. This would allow users to run games in an isolated environment, providing an additional layer of security. In the event of malicious code or unwanted changes, they would not affect the main system.

Custom Launch Parameters:
Introducing a feature that allows users to set their own launch parameters through other applications. This will provide flexibility in managing game launches; for example, users could implement additional security settings or pre-launch checks.

These improvements will not only enhance security but also add more functionality, which will undoubtedly be appreciated by our users.

Thank you for considering this proposal! I look forward to discussing ideas and making any necessary additions.

**Comment by r37r05p3C7** [comment]
1. Sandboxie is a Windows-only solution.
2. If you are concerned about malware, spin up a virtual machine and run your games inside it.
3. Platform-native batch/powershell/shell scripts already provide infinite levels of flexibility in how you launch your applications. Implementing a custom solution is unnecessary.

**Comment by Willy-JL** [comment]
i have to agree with that, but appreciate the suggestion anyway
