### ISSUE TITLE
Minor visual bugs

### ISSUE THREAD

**Issue by r37r05p3C7** [Willy-JL/F95Checker#119]
1. Scrollbar is always visible in popups. ~~I'm only bringing this up because i noticed that X version does not have this issue. I failed to locate any commits related to the popus in the X commit history, so it might be something introduced after its demise here.~~ same issue in X with scaling factor >1

2. Tag widget artifacts?
![image](https://github.com/Willy-JL/F95Checker/assets/153987701/485c2e86-9c42-45f1-a2ea-612190ddc3fa)

**Comment by Willy-JL** [comment]
What interface scaling factor do you use?

**Comment by Willy-JL** [comment]
?

**Comment by Willy-JL** [comment]
I have found the cause of the issue, but not sure on a fix yet... why close?

**Comment by Willy-JL** [comment]
> btw, app straight up crashed when i tried to apply scaling factors above 2.5

normal behavior, sort of. imgui uses a opengl texture for font data, and those have a limited size depending on platform, though it usually is about the same. it is puzzling that it crashed however. it should reset to previous value
