### ISSUE TITLE
Spoilers are not cut on non-English forum UI settings

### ISSUE THREAD

**Issue by ArchmageFil** [Willy-JL/F95Checker#12]
if I understand correctly, [line 300 in api.py](https://github.com/Willy-JL/F95Checker/blob/874f5fcf544a57a984c70847d714b6d202e20be6/modules/api.py#L300) is responsible for this. To fix, you need an additional replacement for "Спойлер"

![spoilers_uncut](https://user-images.githubusercontent.com/33095094/175935257-a3b40fba-8b22-4d5d-b3c0-0fae8ba633fe.png)

**Comment by Willy-JL** [comment]
Indeed, checking for the display text is a bad idea. If there's a way to identify all spoilers such as class name or another attribute I'll add some preprocessing that removes the display text from spoilers, otherwise I'll add some translations... thanks for reporting this issue!
