### ISSUE TITLE
[Request] Quick search clearing button

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [Willy-JL/F95Checker#121]
The current search bar is:
<img width="620" alt="image" src="https://github.com/Willy-JL/F95Checker/assets/7605896/d4283820-056e-4e55-9087-914d4bf666dc">
and there's a bit of work necessary to clear the current search.

It's becoming more and more common to have an 'X' or other rapid-clear button for search text fields. Brave search, for example, has this:
<img width="502" alt="image" src="https://github.com/Willy-JL/F95Checker/assets/7605896/eaf89bac-a21c-4800-8113-d7b5a9902053">

Can we have this, too?

**Comment by Willy-JL** [comment]
you can right click > clear, or press escape on your keyboard

**Comment by ParaplegicRacehorse** [comment]
Hmm.  Go figure, I didn't try that. Things you learn about. Okay, then. Cool.

Can we have a Github-wiki page, or a proper documentation site, with a bunch of tips highlighting all the hidden features?

**Comment by Willy-JL** [comment]
mayhaps
