### ISSUE TITLE
Extension installation will always fail for Chromium because of "CRX_REQUIRED_PROOF_MISSING."

### ISSUE THREAD

**Issue by nazdridoy** [Willy-JL/F95Checker#125]
Since F95Checker tries to install extensions via RPC, it attempts to load http://127.0.0.1:57095/assets/chrome.crx in the browser and expects to auto-install the extension. This method would be very convenient than installing an unpacked extension. but You cannot distribute an extension witch isn't in the Chrome Extension Store. According to the official chrome docs, every extension distributed either from the chrome extension store or outside of it must be uploaded to the chrome extension store. Or you have to modify your local Policies to allow installs from a custom URL. 

Besides, most, if not all, modern browsers would warn users about its "potentially harmful nature", which could probably spook some people. Some browsers might outright delete this file. (vivaldi)

![2024-02-06_03-04](https://github.com/Willy-JL/F95Checker/assets/45564804/1ef7cf5c-35cb-42e8-870c-1fd2d300d810)

Chromium won't let you install CRX without the "Chrome Web Store's publisher key hash."
![2024-02-06_03-05](https://github.com/Willy-JL/F95Checker/assets/45564804/9eb8f3ad-30b4-4f45-901e-ee21b2806fb7)

https://github.com/chromium/chromium/blob/main/components/crx_file/crx_verifier.cc#L97-L270

<details>
  <summary>chromium/components/crx_file
/crx_verifier.cc</summary>
  

```c++
VerifierResult VerifyCrx3(
    base::File* file,
    crypto::SecureHash* hash,
    const std::vector<std::vector<uint8_t>>& required_key_hashes,
    std::string* public_key,
    std::string* crx_id,
    std::vector<uint8_t>* compressed_verified_contents,
    bool require_publisher_key,
    bool accept_publisher_test_key) {
  
	// ...

  if (public_key_bytes.empty() || !required_key_set.empty())
    return VerifierResult::ERROR_REQUIRED_PROOF_MISSING;

  if (require_publisher_key && !found_publisher_key)
    return VerifierResult::ERROR_REQUIRED_PROOF_MISSING;

	// ...

VerifierResult Verify(
    const base::FilePath& crx_path,
    const VerifierFormat& format,
    const std::vector<std::vector<uint8_t>>& required_key_hashes,
    const std::vector<uint8_t>& required_file_hash,
    std::string* public_key,
    std::string* crx_id,
    std::vector<uint8_t>* compressed_verified_contents) {
  std::string public_key_local;
  std::string crx_id_local;
  base::File file(crx_path, base::File::FLAG_OPEN | base::File::FLAG_READ);

  // ...

  // Version number.
  const uint32_t version =
      ReadAndHashLittleEndianUInt32(&file, file_hash.get());
  VerifierResult result;
  if (version == 3) {
    bool require_publisher_key =
        format == VerifierFormat::CRX3_WITH_PUBLISHER_PROOF ||
        format == VerifierFormat::CRX3_WITH_TEST_PUBLISHER_PROOF;
    result = VerifyCrx3(
        &file, file_hash.get(), required_key_hashes, &public_key_local,
        &crx_id_local, compressed_verified_contents, require_publisher_key,
        format == VerifierFormat::CRX3_WITH_TEST_PUBLISHER_PROOF);

```

</details>

**Comment by Willy-JL** [comment]
even this research looks pretty grim on the matter https://blog.janestreet.com/chrome-extensions-finding-the-missing-proof/

**Comment by Willy-JL** [comment]
cant even make chrome open chrome://extensions, neither via cli, nor via default open, nor via redirect. this is great.

**Comment by Willy-JL** [comment]
> I'd suggest you not package these extensions with the program; it's kind of a bad practice. Instead, you can build these extensions separately and update them when needed. Create a GitHub page to serve extension archives (redirect from the GUI) and provide proper documentation. You have built a very useful tool, but it is in extreme need of proper documentation describing all its features and FAQs

sounds like effort

**Comment by Willy-JL** [comment]
i made it pop up an explanation for chrome, when accepted it shows an explorer window where chrome.zip can find. should atleast be easier than before, although still not as i wouldve liked it by installing via local webserver. this is good enough, i will not lose more time on google's tyranny.

**Comment by Willy-JL** [comment]
> i made it pop up an explanation for chrome, when accepted it shows an explorer window where chrome.zip can be found. should atleast be easier than before, although still not as i wouldve liked it by installing via local webserver. this is good enough, i will not lose more time on google's tyranny.
> 
> see [3152bcc...8462fec](https://github.com/Willy-JL/F95Checker/compare/3152bccf085b767bc82489b8c6811f94f581a297...8462fecfc62c86ba1eaa7ed413bc6e66b39a1b24)

also, this approach solved the criticism over the proposed appimage distribution. this way, the user doesnt need to go digging for the file to drag and drop, it is shown to them directly.

**Comment by Willy-JL** [comment]
> i agree. as appimages mounts its AppDir with random characters added to the end of its path. opening file explorer at self_path would the best option.

yep. i wouldve wanted it to be step by step, like click ok to open the extensions page, then you click next to show the chrome.zip file, but chrome said no and you cant open chrome:// urls from cli

**Comment by Willy-JL** [comment]
> and please, try to think of a way to make it a bit more verbose, at least when someone runs it from the CLI. My personal build (with some minor tweaks ) crashed with a 'segmentation fault (core dumped),' and the debug executable didn't provide any information either. While it's nice when programs run without spitting out 30 lines of log messages, bot when someone actively chooses to run it through the terminal and gets no information (absolutely nothing) while trying to debug, it's frustrating. Please give some thought to debugging and troubleshooting.

ill try to. but if its a segmentation fault, it is very likely something is wrong with either the browser, or how it is compiled, or with your python install

**Comment by Willy-JL** [comment]
> `google-chrome --new-window chrome://desired-url` works

maybe for you, but not for me. and not for most of the web from what ive seen, im not the only one this doesnt work for.

**Comment by Willy-JL** [comment]
https://superuser.com/questions/1783506/how-to-open-chrome-pages-from-linux-terminal

**Comment by Willy-JL** [comment]
that coudl work yeah, but i think step by step is fine for now
