### ISSUE TITLE
Console windows stays open

### ISSUE THREAD

**Issue by MCUxDaredevil** [Willy-JL/F95Checker#13]
I just updated to the latest release 9.0
Every time I run the executable, a console window opens up alongside and just shows this message:

`Redirecting stdout and stderr to I:\F95Checker-Windows\log.txt`

Closing the windows also exits the app. Is there a way to keep the running without the console?

**Comment by Willy-JL** [comment]
Thing is, it should have hidden itself... I’ll look into it later

**Comment by Willy-JL** [comment]
How are you launching it?

**Comment by MCUxDaredevil** [comment]
> How are you launching it?

The exe file

**Comment by Willy-JL** [comment]
Can you try the [latest build](https://github.com/Willy-JL/F95Checker/actions/runs/2767161340)?

**Comment by MCUxDaredevil** [comment]
It works now
Thanks!
