### ISSUE TITLE
Release cycle?

### ISSUE THREAD

**Issue by Uatschitchun** [Willy-JL/F95Checker#133]
Hi there. 

Last release is from 04/23. This is 10 month now.

Is there something holding back from releaseing more often?

**Comment by Willy-JL** [comment]
busyness with other projects, and wanting to fix some regressions with wayland

**Comment by Uatschitchun** [comment]
It was meant in general, like some kind of release cycle...

**Comment by Willy-JL** [comment]
when its ready and i feel like releasing

**Comment by Willy-JL** [comment]
im hoping to get a release ready within next few days
