### ISSUE TITLE
`Add Exe` allows adding non-executables

### ISSUE THREAD

**Issue by FaceCrap** [Willy-JL/F95Checker#142]
I noticed that when you add an executable, you can inadvertently also add non-executables.

Might be an idea to have the file browser dialog show executables only instead of testing whether the selected file is actually executable.

**Comment by Willy-JL** [comment]
it is intended that you can select non-executables. you could be selecting a video file, or an html file.

**Comment by FaceCrap** [comment]
An HTML file I can understand, but a video file? Isn't the checker intended to track games? It might be that I never encountered one, but are there really games using a video file format as launcher?

**Comment by Willy-JL** [comment]
There's collections. And there's some "games" that are just a flash program to select scenes in a video, and someone extracted just the video and posted it. Im looking at you, Affect3D Miro
