### ISSUE TITLE
linux flatpak browsers do not show up in dropdown menu

### ISSUE THREAD

**Issue by loongemperor** [Willy-JL/F95Checker#153]
the dropdown selection for browsers to open links with in linux only shows browsers that are installed as system package and not browsers that are installed as flatpak

tested on linux mint cinnamon v21.3
tested flatpak browsers (does not show up):
brave
mullvad
tor
librewolf
google chrome
waterfox

tested system browsers (does show up and work):
firefox
thorium

I am actually not sure how to even go about interacting with flatpak for this.

**Comment by sonikun** [comment]
Same issue. Did you find any fix?

**Comment by Willy-JL** [comment]
You can setup custom browser with executable flatpak and arguments run your.flatpak.id 

Anyway since I've started to use flatpak myself too, I will probably fix this when I get back to working on f95checker
