### ISSUE TITLE
Backup entire Library?

### ISSUE THREAD

**Issue by sonikun** [Willy-JL/F95Checker#154]
There is an export option but it exports only threadlinks. How do I export all the stuff like notes, rating, threadlinks to back it up?

**Comment by sonikun** [comment]
@FaceCrap any solution for this?

**Comment by FaceCrap** [comment]
I'm not the dev, but if you go read The FAQ, it tells where the data is stored. Backup that?

**Comment by Willy-JL** [comment]
Yeah just backup the db.sqlite3 file in data folder
