### ISSUE TITLE
RPC server error when launching the app 

### ISSUE THREAD

**Issue by Laseracid** [Willy-JL/F95Checker#157]
error message in the text is 

Traceback (most recent call last):
  File "D:\a\F95Checker\F95Checker\modules\rpc_thread.py", line 92, in run_loop
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\socketserver.py", line 456, in __init__
  File "C:\hostedtoolcache\windows\Python\3.11.2\x64\Lib\socketserver.py", line 472, in server_bind
PermissionError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
![2024-05-02 09_48_26-f95checker](https://github.com/Willy-JL/F95Checker/assets/8929732/43655c44-a902-4343-b3ef-5ee70e9a4e3f)

I've added the app to Windows firewall so it should have full access to the internet and on my router I have f95 unblocked just in case. 

Not sure what the error message is barking about the app still is pulling down comments and game updates,

**Comment by Willy-JL** [comment]
Don't open it on the router, it only needs to be on the pc itself, it's localhost. But your antivirus is doing something weird. Not much I can do to help

**Comment by Laseracid** [comment]
I just unblocked the site f95 as it was getting caught but my spam blocker that's all I meant by that I'm not opening the port in the error message.

the spam block issue was something long before I started using this app.

**Comment by Willy-JL** [comment]
As I said it's gonna be your antivirus doing something weird on your pc. And if you read what the error message very clearly tells you this does not affect connecting to f95zone, this is a feature of f95checker on your px only. Read the error message again. And if it's something you care about, fix your antivirus, or disable the feature if not.

**Comment by Laseracid** [comment]
I just use the built-in Windows Defender I'll try turning it off and relaunching the app but if not I don't use the Chrome ext should I just turn the server off?

**Comment by Laseracid** [comment]
I turned off the RPC server in the app as it was giving the same error when I had Windows Defender disabled.  I'm not sure what caused it I've never had any other AV app installed on the PC and the Windows 11 install is only about 10 months old.
