### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MikeCZ23** [Willy-JL/F95Checker#16]
update.bin
https://www.uschovna.cz/zasilka/AW9R8TTB7C3IWHG4-RUP/

**Comment by Willy-JL** [comment]
I, and basically everone on this platform, would appreciate if you used a more standard file hoster. For the future, github supports uploading files by just dragging and dropping them into the comment box.

That is a very generic errror from github api, not much i can do with it. My guess is that github has shadowbanned your ip address and so it returns garbage api responses. For now i will add a simple popup saying that it failed and that it might be a temporary issue, if the issue remains after a few days then im not quite sure, youre the only one with this issue and its not a problem with my code.
