### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by Crystal-RainSlide** [Willy-JL/F95Checker#162]
Would be helpful to connection problems.

If this requires some extended time to develop, change the program to follow system proxy by default can be a start.

To everyone who is facing connection problems and want to use proxy: [proxychains-windows](https://github.com/shunf4/proxychains-windows) is not working perfectly by default, since F95Checker need to start a RPC server to connect with its browser extension.

Error message when using proxychains-windows for proxy:

```
Failed to start RPC server on localhost port xxxxx:
OSError: [winError10049]

This means that the web browser extension will not work, while F95Checker
itself should be unaffected. Some common causes are:
- Hyper-V
- Docker
- -Antivirus or firewall
```

**Comment by Willy-JL** [comment]
I think proxy support is out of scope for this tool. I suggest a systemwide solution / vpn

**Comment by Crystal-RainSlide** [comment]
VPN should always work, but some just use socks5 proxy. And, even now, there is still no very good socks/HTTP-proxy-to-VPN solution (expect for SocksDroid on Android, maybe).

I think a systemwide solution on Linux is possible (but yet to find out), so do Mac;

However, on Windows, THE systemwide solution is the system proxy, and it don't follow the system proxy like other programs. Moreover, a common solution to this situation, proxychains-windows, don't work perfectly by default - later I'll try fiddle with it and see if I can make the local RPC server work with proxychains-windows.
