### ISSUE TITLE
Auto update to latest version

### ISSUE THREAD

**Issue by soni0212** [Willy-JL/F95Checker#17]
When I opened the checker today I saw a message that update was available and it would delete everything in that folder so I pressed "no" and made a backup(was nervous lol) but now after relaunching the update wont show
Do I have to manually do it? if yes then how? and will it delete the current notes ratings etc?

**Comment by Willy-JL** [comment]
It will run an update check after a refresh at 6 hour intervals. Closing it will reset the interval and will check again on the first refresh. Maybe you didn’t fully close it because maybe you had “minimize to bg on close”?
