### ISSUE TITLE
Future request: Last version played

### ISSUE THREAD

**Issue by TYRS0** [Willy-JL/F95Checker#174]
Currently when a game is uninstalled the program removes the version number that you had. Could it save that information instead? it would make it a better user experience when going through recently updated games, because at the moment it is annoy to cross refence dates to figure out how many updates happened since you last played it. when a game updates it gets a star that when you hover over tells you the version number of the update and what you have downloaded, that would be a perfect spot to replace or add a last played version either for just uninstalled games or all as a whole.

**Comment by FaceCrap** [comment]
Hot sure what you mean, The checker does not keep track of games on disk, so if you remove a game from your HD (as I do after playing it) the version(s) listed in the checker stay as they were. 
So the version listed right after the name is either the one from when your marked it as played, or if you removed the game without marking it as played, the last installed version

**Comment by TYRS0** [comment]
sorry for the confusion. what i was talking about is when the game is marked as uninstalled and then a new version is added to F95, the version number gets replaced with the new one but there is no way to tell what was the last version you played. i have since found a workaround or the proper way of doing things. Marking games as finished saves the version number that was finished and it persists after a new version is added.

**Comment by Willy-JL** [comment]
> i have since found a workaround or the proper way of doing things. Marking games as finished saves the version number that was finished and it persists after a new version is added.

wouldnt call that a workaround, this is exactly its intended purpose :D just a way to remember what you have / havent played, regardless of whether you have it installed or not

**Comment by Willy-JL** [comment]
can this be marked as completed then?

**Comment by TYRS0** [comment]
Done
