### ISSUE TITLE
Thread Parsing Error: Failed to parse necessary sections in thread response

### ISSUE THREAD

**Issue by ImanonymousOne** [Willy-JL/F95Checker#175]
Application will not update, fails with 'Failed to parse necessary sections in thread response, the html file has been saved to C:\Temp
Please submit a bug report on F95Zone or Github including this fle. 
[broken.zip](https://github.com/user-attachments/files/17616342/broken.zip)

**Comment by ImanonymousOne** [comment]
Currently using F95checker 11. beta 1143, as recommended by you, have been for over 6 months with no issues, v10.2 will not and has not worked for me in over 12 months due to the following issue
 ({ "status": "error",   "msg": "Invalid threads data or >100"}

**Comment by sonikun** [comment]
Facing the same when refreshing
![image](https://github.com/user-attachments/assets/b6dd99f5-8200-4261-ab3a-d60ef8fc88bd)
![image](https://github.com/user-attachments/assets/7f45d032-5621-4637-97a0-d4e5a56784eb)

**Comment by Willy-JL** [comment]
rate limiting, looks like forum changed some stuff. ugh. i dont have the time to look into this now.

> v10.2 will not and has not worked for me in over 12 months due to the following issue
({ "status": "error", "msg": "Invalid threads data or >100"}

this is because new versions changed how we store whether a game is custom or not. the old version doesnt know this, so it thinks custom games are f95zone games, but forum does not know these thread IDs so it gives an error

NEVER downgrade versions unless i explicitly instruct you to do so, or if you have no other option (but do so at your own risk)

**Comment by ImanonymousOne** [comment]
@Willy-JL  I  have not downgraded the version, simply stating why I am currently using F95checker 11. beta 1143, as this was the only version that works for me, or it did until this current 'Thread Parsing Error" issue
Can you do something to fix this bug please?

**Comment by ImanonymousOne** [comment]
@Willy-JL  Thanks, seems to have resolved the issue

**Comment by Willy-JL** [comment]
i didnt fix any issue yet lol

its a 429 too many requests, it wont always happen. the checker makes rwquests too fast for what f95zone allows, but it doesnt always reach the limit. and if it does reach the limit, you can just retry.

**Comment by Willy-JL** [comment]
did not mean to close this issue. still however, the problem should be resolved now, please try the latest beta version

**Comment by ImanonymousOne** [comment]
@Willy-JL  Downloaded 11.0 beta 1232 and have been using it, no errors on refresh so far, Chrome plugin works OK as well

**Comment by sonikun** [comment]
Sorry or the noob question but how do I try the latest beta version? Releases has app from 2023, do I build it myyself?

**Comment by Willy-JL** [comment]
Seems like you figured it out, but it's explained in FAQ in the readme
