### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by gimpyestrada** [Willy-JL/F95Checker#177]
For the first time today I've received an error message pointing at an HTML file that has this message:

429 - Too Many Requests . That’s an error.

Client issued too many requests. That’s all we know.

This has now happened three times when trying to do a full request.  

I was able to close the app, wait a few and open it again and it picked back up where it left off.  I currently have 647 games that I'm tracking.

**Comment by Whatthee** [comment]
See my previous post https://github.com/Willy-JL/F95Checker/issues/176

**Comment by gimpyestrada** [comment]
I'm closing this one as a dupe.
