### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by yohudood** [Willy-JL/F95Checker#18]
I got this error today
ps rename login_broken.bin.log to login_broken.bin
![image](https://user-images.githubusercontent.com/7326070/182636379-df20d5c2-cd32-42a0-ace7-160ef84ceb22.png)
[login_broken.bin.log](https://github.com/Willy-JL/F95Checker/files/9252433/login_broken.bin.log)

**Comment by Willy-JL** [comment]
F95zone is down right now, you can check the #status on the f95zone discord server

**Comment by yohudood** [comment]
it works now i dit not see know f95 was down
