### ISSUE TITLE
Failure to open application correctly - no errors displayed - after having previously opened it once before

### ISSUE THREAD

**Issue by Camarron** [Willy-JL/F95Checker#191]
I'm not sure how to describe this bug.
Essentially, on my system, I'm only able to open a f95zoneschecker application one time ever. Then it fails to open a Window but leaves the process running in my list.
This behavior is repeatable by me by deleting all contents of the installation folder, then unpacking the latest build for windows from the Actions tab.
I am able to open the application correctly one time.And when closed, it never opens again.
This behavior is persistent through reboots, etc. I do not configure the app to run on boot, either.
This behavior happens if I delete the app  installation folder content and unzip the same build package into it as well.

**Comment by Willy-JL** [comment]
Sounds to me like your antivirus is being a bitch and deleting shit from the program folder. Try to add an exclusion to the antivirus for the folder you put f95checker in.
Also please specify what version you use, and try the latest beta if you aren't using it yet, but still it sounds like something is touching the program's files when it shouldn't

**Comment by Camarron** [comment]
I would Agree, but I don't use any AV besides Defender. And it is constantly reporting no actions in any log I can find within it. But I'l gonna try this right now by deleting my install folder  contents, adding it to the exclusion list in defender, then downloading and extracting into said folder.
![image](https://github.com/user-attachments/assets/5686b381-5d31-4a71-a04c-e65c544bcc9b)
And this is the beta build I'm attempting this on.
![image](https://github.com/user-attachments/assets/b6542166-4bae-4158-b689-fe15d98f44a3)
And there is no effect. Doesn't launch the application window, just the process.
i'm going to try just running the beta build from a different location.
And nothing happens. I did it from a different location and nada.
It just loads up into ram 254mb and then never does anything

Anything in specific you need?

**Comment by Camarron** [comment]
Ok, my apologies. My Mistake. I did all the above, and it was exactly as described. But I just attempted to launch it while that process was running, by executing the main file again. And now it opens.
I am able to repeat this behavior by opening the file twice.
When opened twice, it launches correctly.

**Comment by Willy-JL** [comment]
@Camarron you enabled this:
![image](https://github.com/user-attachments/assets/a983c4ad-0a35-4e6c-9313-5530ddc7e800)
it starts in background, in the system tray. launching a second time it tells the existing process in background to show the interface.
and you also have this enabled:
![image](https://github.com/user-attachments/assets/fd0162a0-e4e5-4563-b00f-82adc26b235f)
which means that closing the tool does not actually close it, instead it gets put in background mode.

**Comment by Camarron** [comment]
Oh my god. I did. I'm sorry. Thanks for the help brother.
