### ISSUE TITLE
Ability to get notifications/view for all new games (or updates)

### ISSUE THREAD

**Issue by GoldenAngel2** [Willy-JL/F95Checker#195]
- https://f95zone.to/sam/latest_alpha/latest_data.php?cmd=rss&cat=games
returns a list of the latest games, so it would be pretty cool if there was a button/toggle to enable getting notified for all latest games even if you don't have it explicitly added to the main tracker.
> There is also more filtering options for the feed as well, similar to the main https://f95zone.to/sam/latest_alpha/ page. 

- Features: 
 - View latest games added / updated.
 - Get notifications for when a new game gets added or an existing game gets updated.

**Comment by Willy-JL** [comment]
I don't see how having it in app is any more beneficial than having it in browser. The app solves a very specific usecase that the browser version of f95zone doesn't allow you to do. This is outside the scope of this project
