### ISSUE TITLE
MacOS can’t find QWebEngineProcess

### ISSUE THREAD

**Issue by tibucci** [Willy-JL/F95Checker#20]
Can't refresh on macOS, apps crash and gives out errors.
Seen other comments like this on the f95 thread and that you know it's a problem. just putting this here so it's easier to track whether you solved it or not. 
Really looking forward to using this and finally have a little organization

**Comment by Willy-JL** [comment]
I don't think it's the same issue, what users were reporting was an issue with the login window not opening, and the log.txt saying that qt couldn't find QtWebEngineProcess, aka the browser engine for the login window. But it would just fail to refresh due to being unable to login, it wouldn't crash. If your issue is different go ahead and send you log.txt

**Comment by tibucci** [comment]
Thank you for the prompt answer!
I'm attaching the log and screenshot of the errors.
The system message is the first to appear (sorry it's in italian) and states that the app closed unexpectedly, so I guessed a component or something inside is crashing. The app in itself is still open and responsive

[log.txt](https://github.com/Willy-JL/F95Checker/files/9296726/log.txt)
<img width="1280" alt="Schermata 2022-08-10 alle 06 26 04" src="https://user-images.githubusercontent.com/17724143/183816049-d82b6561-6173-4fab-9766-05be3ab54e70.png">
<img width="1280" alt="Schermata 2022-08-10 alle 06 25 48" src="https://user-images.githubusercontent.com/17724143/183816065-a29da04f-541d-4940-b50b-8077286327ce.png">

**Comment by Willy-JL** [comment]
Ok yeah it actually is the same error. To open the login window it spawns a new child process, but in your case that process fails to find the web engine process so the child process crashes...

**Comment by RRCN08** [comment]
> Ok yeah it actually is the same error. To open the login window it spawns a new child process, but in your case that process fails to find the web engine process so the child process crashes...

Any update on this? Facing the same issue.

**Comment by Willy-JL** [comment]
Im not a mac user so i have to resort to using a macos virtual machine, which apparently is not even capable of running opengl so the graphical part of my app wont work at all for me, so debugging this will be a bit difficult for me. also considering the amount of mac users is quite low compared to the other platforms and that i am very unfamiliar with the ecosystem this is relatively low priority for now, sorry :/

**Comment by RRCN08** [comment]
That’s cool yo. As a workaround, Mac users can use the windows version and
just copy over the db file from windows to Mac, it should work flawlessly.
Thanks for the efforts!

**Comment by tibucci** [comment]
> That’s cool yo. As a workaround, Mac users can use the windows version and just copy over the db file from windows to Mac, it should work flawlessly. Thanks for the efforts!
Wait whaaat... how does that work?
Do I have to keep the app on a windows machine and copy the database over after every update, added game and change or is it a one time thing?

**Comment by RRCN08** [comment]
> That’s cool yo. As a workaround, Mac users can use the windows version and just copy over the db file from windows to Mac, it should work flawlessly. Thanks for the efforts!
> Wait whaaat... how does that work?
> Do I have to keep the app on a windows machine and copy the database over after every update, added game and change or is it a one time thing?

haha, I have updated my response, check it out. Its a one time thing. Every function works flawlessly.

**Comment by tibucci** [comment]
Thank you for your work😊

**Comment by Willy-JL** [comment]
After a lot of struggles, i found out that webkitgtk doesn't even work on windows so a full switch to gtk is not an option... i might try to make platform specific implementations so that atleast linux and macos might be spared from the pain of qt hell, but we'll see...

**Comment by Willy-JL** [comment]
Can you guys try to see if this is fixed with [build 691](https://github.com/Willy-JL/F95Checker/actions/runs/3459301761)? it is still using qt and qwebengineprocess, but i am invoking it differently, and in the more intended way so im hoping this fixes the issue...

**Comment by Willy-JL** [comment]
I am fairly confident that [build 698](https://github.com/Willy-JL/F95Checker/actions/runs/3465660254) should fix this issue

**Comment by Willy-JL** [comment]
Released in [version 9.5](https://github.com/Willy-JL/F95Checker/releases/tag/9.5)
