### ISSUE TITLE
Chrome extension icon is messed up

### ISSUE THREAD

**Issue by sisco1986** [Willy-JL/F95Checker#202]
the icon that shows you have a game added on the f95 checker is really messed up on the website, it just shows as a black square
![image](https://github.com/user-attachments/assets/82b4856a-766a-45bc-9640-c652b6ee1566)

**Comment by Willy-JL** [comment]
can you check in devtools network tab, refreshing the page, if theres a failed request for `http://127.0.0.1:57095/assets/mdi-webfont.ttf`

**Comment by FaceCrap** [comment]
@sisco1986 
I only have Chrome Portable installed, but I get to see an icon
![image](https://github.com/user-attachments/assets/1c047d67-9abd-476f-a2d3-0f6794cf0008)

On the network tab, it's easier to limit the output to fonts only like so
![image](https://github.com/user-attachments/assets/27353a4d-ee36-46bd-8e0d-dd40cd8f102e)

You probably will have a different status code for the font @Willy-JL metnioned
![image](https://github.com/user-attachments/assets/e694994b-16e5-4339-9db4-59db24994905)

**Comment by sisco1986** [comment]
yeah, it's getting blocked by the brave addblocker 
![image](https://github.com/user-attachments/assets/694136ab-c295-42e2-839c-73285dc3e0e5)
![image](https://github.com/user-attachments/assets/b979e597-e096-4cad-8a10-4928b1388a9a)

**Comment by Willy-JL** [comment]
i see. i think it may be possible to include the font with the extension itself, and load it using chrome extension runtime https://developer.chrome.com/docs/extensions/reference/api/runtime#example-get-url
