### ISSUE TITLE
Open folder button and mid click on open webpage

### ISSUE THREAD

**Issue by Sereyon** [Willy-JL/F95Checker#21]
Please add an option to set the game folder independent of the games executable.

**Why:**
Some games I have to or want to start differently than just running the games executable, e.g. flash games or html with a nondefault browser. Also I like to just keep the compressed game files after finishing a game and deleting the unpacked files, so I can not point the app to the executable.

**How:**
I would suggest to keep the current logic of using the folder containing the executable as game folder if set and override this with a manually set folder. It should be possible to set the games folder without setting the games executable.

**Comment by Willy-JL** [comment]
I feel like your situation could be solved by just setting the executable as the zip file, and then middle clicking the play button to open the folder...

**Comment by Sereyon** [comment]
I was not aware of this middle click feature. That indeed is a viable solution. Thank you.

**Comment by Willy-JL** [comment]
To be fair I think I'll even this out with the open thread / copy link:
- add a column with "open folder" buttons
- make middle click on "open webpage" copy the thread link

**Comment by Willy-JL** [comment]
Released in 9.4
