### ISSUE TITLE
Tracking via other devices(kinda)

### ISSUE THREAD

**Issue by ogkimra** [Willy-JL/F95Checker#23]
I'm someone who has like 150+ games in the checker.. so sometimes I want to recheck(when i'm away from my desktop) which game updates were out the last time I refreshed the checker.. I think it could be achieved by linking our email or something?

I'm no developer but I wanted to ask if there is any way we could add our email or apps(like todo or notion) to get the updated games in a list or some format with forum links directly.

Sorry I don't know if it is doable for you
Thankyou for your amazing work!

**Comment by Willy-JL** [comment]
This seems mostly outside the scope of the tool and also quite clunky of a system. For now id suggest using some remote desktop software like maybe anydesk. In the future i might consider alternatives but not for now sorry
