### ISSUE TITLE
error pip3 install -U -r requirements.txt (debian 10)

### ISSUE THREAD

**Issue by yohudood** [Willy-JL/F95Checker#26]
Building wheel for imgui (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for imgui (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-39
      creating build/lib.linux-x86_64-cpython-39/imgui
      copying imgui/__init__.py -> build/lib.linux-x86_64-cpython-39/imgui
      copying imgui/extra.py -> build/lib.linux-x86_64-cpython-39/imgui
      copying imgui/_compat.py -> build/lib.linux-x86_64-cpython-39/imgui
      creating build/lib.linux-x86_64-cpython-39/imgui/integrations
      copying imgui/integrations/sdl2.py -> build/lib.linux-x86_64-cpython-39/imgui/integrations
      copying imgui/integrations/pyglet.py -> build/lib.linux-x86_64-cpython-39/imgui/integrations
      copying imgui/integrations/pygame.py -> build/lib.linux-x86_64-cpython-39/imgui/integrations
      copying imgui/integrations/glumpy.py -> build/lib.linux-x86_64-cpython-39/imgui/integrations
      copying imgui/integrations/glfw.py -> build/lib.linux-x86_64-cpython-39/imgui/integrations
      copying imgui/integrations/opengl.py -> build/lib.linux-x86_64-cpython-39/imgui/integrations
      copying imgui/integrations/cocos2d.py -> build/lib.linux-x86_64-cpython-39/imgui/integrations
      copying imgui/integrations/base.py -> build/lib.linux-x86_64-cpython-39/imgui/integrations
      copying imgui/integrations/__init__.py -> build/lib.linux-x86_64-cpython-39/imgui/integrations
      running egg_info
      writing imgui.egg-info/PKG-INFO
      writing dependency_links to imgui.egg-info/dependency_links.txt
      writing requirements to imgui.egg-info/requires.txt
      writing top-level names to imgui.egg-info/top_level.txt
      reading manifest file 'imgui.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      no previously-included directories found matching 'imgui-cpp/extra_fonts'
      adding license file 'LICENSE'
      writing manifest file 'imgui.egg-info/SOURCES.txt'
      copying imgui/ansifeed.pxd -> build/lib.linux-x86_64-cpython-39/imgui
      copying imgui/cimgui.pxd -> build/lib.linux-x86_64-cpython-39/imgui
      copying imgui/common.pyx -> build/lib.linux-x86_64-cpython-39/imgui
      copying imgui/core.cpp -> build/lib.linux-x86_64-cpython-39/imgui
      copying imgui/core.h -> build/lib.linux-x86_64-cpython-39/imgui
      copying imgui/core.pxd -> build/lib.linux-x86_64-cpython-39/imgui
      copying imgui/core.pyx -> build/lib.linux-x86_64-cpython-39/imgui
      copying imgui/enums.pxd -> build/lib.linux-x86_64-cpython-39/imgui
      copying imgui/enums_internal.pxd -> build/lib.linux-x86_64-cpython-39/imgui
      copying imgui/internal.cpp -> build/lib.linux-x86_64-cpython-39/imgui
      copying imgui/internal.h -> build/lib.linux-x86_64-cpython-39/imgui
      copying imgui/internal.pxd -> build/lib.linux-x86_64-cpython-39/imgui
      copying imgui/internal.pyx -> build/lib.linux-x86_64-cpython-39/imgui
      running build_ext
      building 'imgui.core' extension
      creating build/temp.linux-x86_64-cpython-39
      creating build/temp.linux-x86_64-cpython-39/config-cpp
      creating build/temp.linux-x86_64-cpython-39/imgui-cpp
      creating build/temp.linux-x86_64-cpython-39/imgui
      x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DPYIMGUI_CUSTOM_EXCEPTION -Iimgui-cpp -Iansifeed-cpp -I./imgui -Iimgui -Iconfig-cpp -I/usr/include/python3.9 -c config-cpp/py_imconfig.cpp -o build/temp.linux-x86_64-cpython-39/config-cpp/py_imconfig.o -includeconfig-cpp/py_imconfig.h
      x86_64-linux-gnu-gcc: fatal error: cannot execute ‘cc1plus’: execvp: No such file or directory
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for imgui
Successfully built PyOpenGL-accelerate
Failed to build imgui
ERROR: Could not build wheels for imgui, which is required to install pyproject.toml-based projects

**Comment by Willy-JL** [comment]
Those packages, since the features required are not yet public, need to be built from source, and you're missing some build requirements.
Run `sudo apt-get install g++`

**Comment by yohudood** [comment]
thanks it works now
