### ISSUE TITLE
Could not find the Qt platform plugin "windows" in "" (Windows 10 Home)

### ISSUE THREAD

**Issue by tommyshelby9121** [Willy-JL/F95Checker#34]
Worked fine after installation, ran into this problem after a few days of use, re-installed, and worked fine for about a week and a half. Just tried running it, a console opens for a split second, closes, and then nothing. Even tried running as administrator, but still nothing. Worked just fine earlier today, around 8-ish hours ago.

Did check StackOverflow, however, since personally, I'm not that well versed with Python, wasn't entirely sure about the solutions presented.

Here is the full output in the `log.txt` file.

```
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
````

`P.S.` This program was suggested by a friend, he hasn't had any issues with the program thus far and runs Windows 10 as well

**Comment by Willy-JL** [comment]
Might be related to #28 , do you have any non ascii (ascii is essentially letters, numbers, and basic symbols like `!_-=?`, but letters with accents are NOT ascii) characters in the path to where your installation is?

**Comment by tommyshelby9121** [comment]
No, I do not have any non-ascii characters in the path to where my installation is.

**Comment by essaion** [comment]
If I may, would you mind posting the whole path to the "F95Checker" directory on your system? If it's private enough, maybe just send it to @Willy-JL as a DM?

**Comment by tommyshelby9121** [comment]
> If I may, would you mind posting the whole path to the "F95Checker" directory on your system? If it's private enough, maybe just send it to @Willy-JL as a DM?

`D:\AVNs\F95 Checker` here ya go

**Comment by Willy-JL** [comment]
> > If I may, would you mind posting the whole path to the "F95Checker" directory on your system? If it's private enough, maybe just send it to @Willy-JL as a DM?
> 
> `D:\AVNs\F95 Checker` here ya go

i doubt it, but maybe its due to the space character in the path... just try without it. otherwise, since you mentioned that it worked fine and then stopped working suddenly, it could be a antivirus problem, deleting your files... maybe try a folder exclusion or something

**Comment by Willy-JL** [comment]
Can you try [build 755](https://github.com/Willy-JL/F95Checker/actions/runs/3511060295)?

**Comment by By-PorfecTo** [comment]
I had the same problem, I solved it with this method

https://www.dosya.tc/server40/9shlzi/fix_f95.rar.html

NOT:

This error is Windows Home, Home Single language is available in windows pro. This error is not present, the program is working properly

**Comment by Willy-JL** [comment]
> I had the same problem, I solved it with this method
> 
> https://www.dosya.tc/server40/9shlzi/fix_f95.rar.html
> 
> follow the steps in the video
> 
> Note: This error only applies to Windows Home and Windows Home Single language
> 
> works fine on windows pro version

1: GitHub supports both video upload and file upload in comments, no need to use to sketchy file hosting.

2: that is not a good solution for countless reasons.

most likely the issue is that you put f95checker in a folder path that contains spaces or special characters. It might be possible that your username has spaces in it so when you put it on the desktop it becomes “C:\Users\Username With Spaces\Desktop”, which might be the issue. Try putting it in C:\F95Checker-Windows, and I bet it will work out if the box

**Comment by By-PorfecTo** [comment]
yes the problem is in custom name and space. But changing the username doesn't work

1. solution: As a definitive solution, windows should be completely deleted and reinstalled, and the username should not contain a special name.

2. solution: create and use a new user with no custom name

If the connection is causing problems, I can remove it.

**Comment by Willy-JL** [comment]
> yes the problem is in custom name and space. But changing the username doesn't work
> 
> 1. solution: As a definitive solution, windows should be completely deleted and reinstalled, and the username should not contain a special name.
> 2. solution: create and use a new user with no custom name
> 
> If the connection is causing problems, I can remove it.

The solution is putting f95checker in some place without a space in the path. If you decide to put it in C:\F95Checker, or decide to reinstall window with a new username and THEN put it on the desktop, that’s your choice, but both will equally work, and I know I would just move it to C:\F95Checker without reinstalling anything

**Comment by By-PorfecTo** [comment]
yes, it only works if C:\F95Checker is taken to the path. I'm just trying to offer a solution for those who want to run the program from different folders.

**Comment by Willy-JL** [comment]
can you try with one of the latest builds from the actions tab? cx_Freeze was bumped with many improvements to Qt bundling so this might be fixed
