### ISSUE TITLE
Filter removing always takes out first filter item

### ISSUE THREAD

**Issue by just-Addict** [Willy-JL/F95Checker#35]
Version: F95Checker 9.4 beta 514
Platform: Windows 10

When you have multiple filters and click the remove button, instead of the clicked filter, the topmost filter gets removed.

![Filter1](https://user-images.githubusercontent.com/19715616/191979520-c8ec5e7c-e834-4d6a-ab1a-fe819d09743f.jpg) -> ![Filter2](https://user-images.githubusercontent.com/19715616/191979543-97f9564c-da4c-4f54-aa5b-0aee503fae92.jpg) -> ![Filter3](https://user-images.githubusercontent.com/19715616/191979564-36a7b68d-b4d7-4fc2-8896-aee8c7312fe9.jpg)

**Comment by Willy-JL** [comment]
Fixed in 8792eb6dac6f444694f39df92f2a1179aeaebd88, not in any build as of now, pending release

**Comment by Willy-JL** [comment]
Fix released in 9.4
