### ISSUE TITLE
Save filters on exit

### ISSUE THREAD

**Issue by just-Addict** [Willy-JL/F95Checker#36]
Since I rarely (if ever) turn off my PC, I also always have F95Checker running, so I never noticed this, but while testing if my issue with removing filters could be influenced by restarting F95Checker, I discovered that filters aren't saved on exit.

Request: Could you add "Saving Filters" to the default behavior?

**Comment by Willy-JL** [comment]
Maybe, but its very very low priority

**Comment by gimpyestrada** [comment]
I cam here to make this same request.  I have several filters turned on most of the time so it would be nice to either save them or or to have a button that would let you restore a filter set.
