### ISSUE TITLE
Separate status column for sorting

### ISSUE THREAD

**Issue by just-Addict** [Willy-JL/F95Checker#37]
As the subject says, could you make Status a separate column, so I can sort on it? I'd like to group them together while still keeping them showing.

**Comment by ipaqi** [comment]
There's probably no need to sort on it, because there are just 4-5 possible values, and you can filter using them.

**Comment by just-Addict** [comment]
@ipaqi I know that I can filter on them. And it's also not a need but a desire, a personal preference if you will, You know, different users have different preferences. With filtering I only get to see the one filtered on, and if you read my request, I'd like to see all entries, including the various different statuses, but just have them grouped together instead of dispersed throughout the list.  
If I could have both python 3.9.5 and a 3.10x side-by-side without all the issues that presented when I tried, I would have run the source version and just changed it myself, but since that caused numerous issues with all my other python tools due to different dependencies, I had to abort that attempt

**Comment by Willy-JL** [comment]
We'll see

**Comment by Willy-JL** [comment]
Using the existing status option was not really possible because of column indexes and other stuff. Also I prefer leaving it to the user to choose, so instead I made an additional column, disabled by default, that shows the status icons and can be sorted on.

**Comment by Willy-JL** [comment]
Released in [version 9.5](https://github.com/Willy-JL/F95Checker/releases/tag/9.5)
