### ISSUE TITLE
Button to clear search bar

### ISSUE THREAD

**Issue by gimpyestrada** [Willy-JL/F95Checker#39]
I'd like to see a button inside of or next to the search bar to clear the contents and return to the full sort.  A little red X or whatever you want.  I'm just annoyed that I have to go back and forth from the mouse to the keyboard to clear the search.

**Comment by Willy-JL** [comment]
Tried my best to make a small button overlayed on the textbox, but all the clicks were passed onto the textbox...

I opted for an option in the right click context menu instead. Also, now pressing escape will completely clear the bottombar text in any situation (where it makes sense of course)

**Comment by gimpyestrada** [comment]
I guess it's better than nothing.  The button doesn't have to be INSIDE the textbox, it could be literally anywhere around it.

**Comment by Willy-JL** [comment]
Don’t like the look of it tho

**Comment by Willy-JL** [comment]
Released in [version 9.5](https://github.com/Willy-JL/F95Checker/releases/tag/9.5)
