### ISSUE TITLE
High GPU Usage on Windows 10 w/ NVidia Graphics Card

### ISSUE THREAD

**Issue by ipaqi** [Willy-JL/F95Checker#40]
While running, the F95Checker program takes a log of GPU %, for very little discernible reason - I don't know if it's new, I just noticed it in the most recent version

![image](https://user-images.githubusercontent.com/4998016/199052753-2c15f39f-089e-4f91-8d05-db59677315fe.png)

When minimized, GPU usage drops to 0, so that's a nice little workaraound for most of the day, but still something to look into

**Comment by Willy-JL** [comment]
Unfortunately that's just how it is. I chose an uncommon graphical interface toolkit that allows me to code things faster, easier and with more freedom, but that works very differently to common gui frameworks. Essentially it needs to redraw the interface constantly to be interactive and responsive, just like a game would (uses the same type of graphical library under the hood in fact). Next update has some mitigations where it will redraw only when necessary, for example when moving mouse or pressing keys, but while that it happening there will be the same kind of gpu usage. What you can do, both now and when next update comes, is play around with the "vsync ratio"and "render if unfocused" settings in the interface section. make sure to read their tooltips too, they give some good insight.

**Comment by Willy-JL** [comment]
Released in [version 9.5](https://github.com/Willy-JL/F95Checker/releases/tag/9.5)
