### ISSUE TITLE
Bypass DDoS-Guard checks

### ISSUE THREAD

**Issue by Only1P** [Willy-JL/F95Checker#47]
[login_broken.zip](https://github.com/Willy-JL/F95Checker/files/10201230/login_broken.zip)

**Comment by Willy-JL** [comment]
Ok so, DDoS Guard. Great. Thankfully I found [this promising bypass](https://git.gay/a/ddos-guard-bypass) so it's just a matter of porting the main logic over into [modules/api.py](https://github.com/Willy-JL/F95Checker/blob/main/modules/api.py#L56-L97). Actually looks like a decent system, as in it's not some captcha bs or dark magic, its just testing if the "browser" will execute scripts and respond accordingly to the challenge in the page.

**Comment by Willy-JL** [comment]
Still needs testing, but I'm not sure how I could manually force a DDoS-Guard challenge to be requested. At the very least now if there is a challenge and the bypass fails, the user gets a more useful error message saying that a browser challenge was needed and the bypass failed.

**Comment by Willy-JL** [comment]
Released in version 10.0, hopefully it actually works lol
