### ISSUE TITLE
Something went wrong ...

### ISSUE THREAD

**Issue by FaceCrap** [Willy-JL/F95Checker#49]
As the subject says, I got this error popup in build 888 on Windows 10 Pro

![image](https://user-images.githubusercontent.com/95778718/208001307-0b5d03ec-0e1d-4ecc-a956-9e426fae618e.png)

When I came back on Actions after posting the above, I noticed build 890... installed that one and now getting this error:

![image](https://user-images.githubusercontent.com/95778718/208002059-beb81dde-a9f4-49ba-ac55-65c8c66c6b08.png)

Last build that worked for me is 884

**Comment by Willy-JL** [comment]
Thanks for the report! Both distraction errors while making bigger changes on the backend. Also both only on beta builds so nothing to worry about. Just fixed both with 858b2a1cefcb8afbabc1af2f46da1e41e03523b4 and 5ddaea2a2998b8666aefc1378a1093001e3ae293 respectively
