### ISSUE TITLE
Archive games to mute updates

### ISSUE THREAD

**Issue by ogkimra** [Willy-JL/F95Checker#51]
With this we won't receive any update notification for selected threads but the game stays inside checker.. If we add those games from F95 to checker then it will show that its already added but archived, it will helpful to avoid certain fetishes which most devs release month after month that we are not interested in

**Comment by Willy-JL** [comment]
Interesting idea. I’m thinking that archived games show always at the bottom of the list, the name is shown with the “dim text” color option, when updates come they don’t show in the updates popup but they still get update markers, maybe I’ll add an icon next to the name

**Comment by FaceCrap** [comment]
Hmmm, this might come in helpful for games that got banned from F95Zone... Just had one of those pop up. And an "Oops! We ran into some problems." message when accessing the thread. 
Problem is that it will throw that error popup asking if you want to remove the game from the list... Thing is, this might get reverted in the future, so I'd like to keep those games in my list...

**Comment by Willy-JL** [comment]
> Hmmm, this might come in helpful for games that got banned from F95Zone... Just had one of those pop up. And an "Oops! We ran into some problems." message when accessing the thread.
> Problem is that it will throw that error popup asking if you want to remove the game from the list... Thing is, this might get reverted in the future, so I'd like to keep those games in my list...

So, I have some stuff to say about those. Recently I made a realtovwly small change, now they don’t interrupt the refresh, so you get the popup but refresh finishes regardless. Then, I have plans to implement custom games, as in you add a game yourself, that’s not on f95zone, so when the threads vanish you could decide to convert to custom game and it would not be checked at all. As for the mute situation, what I might end up doing actually is that muting will still check the games for updates BUT they won’t appear in update pop ups, then won’t get update markers, and if the thread is missing it will just be silently skipped

**Comment by Willy-JL** [comment]
Released in [version 10.1.1](https://github.com/Willy-JL/F95Checker/releases/tag/10.1.1)
