### ISSUE TITLE
popup stack blown ?

### ISSUE THREAD

**Issue by FaceCrap** [Willy-JL/F95Checker#52]
This one is probably a rare one, I guess it's because I got 3 popups at the same time(?)

I got a popup for a "oops we ran into a problem" situation, (game set to hidden because of rule 7), a popup for some game updates, and a popup that release 10 was out (I'm on 10 build 978)

Seems to be the reason for this one....
![image](https://user-images.githubusercontent.com/95778718/211398474-de2c7125-3087-4e2d-97ca-6b399398896d.png)

**Comment by Willy-JL** [comment]
Hard to say, imgui consolidates at render time, not at define time. Find it hard to believe it really is a stack mismatch, more likely that 2 popups used the same ID. I keep a numeric id that increments with each popup, so what probably happened is 2 different coroutines tried to open a popup at the same time and both managed to get the previous id before the other was able to increment it. No real easy way to fix it, so instead i opted to include the decimal part of the system clock seconds and also a random number string into the popup IDs

**Comment by Willy-JL** [comment]
Released in [version 10.1.1](https://github.com/Willy-JL/F95Checker/releases/tag/10.1.1)

**Comment by FaceCrap** [comment]
Got another one of those...
Update popup for games and notification that a newer version was available (on build 1026, so newer than release version)
![image](https://user-images.githubusercontent.com/95778718/217338617-3e4ec76f-06fe-405f-9cad-557d4935ed14.png)
