### ISSUE TITLE
Game file management/installing

### ISSUE THREAD

**Issue by CuddleBear92** [Willy-JL/F95Checker#53]
Would be great if we could have the program handle game files for you, moving it to a central path with a custom naming scheme as it also points to the path for launching the game. It could also be combined with an extraction tool like 7zip or something.
This way the program can take control over your games folder more easily and your folders will always be sorted.
For example GL allows you to set a scheme like this: `{creator}\{game}\{version}` which will be used at the base game directory you have set. So something like `D:/BaseGAMEPath/creator/title/version/game.exe`
A way to delete the game folder when you delete the version in the UI also makes sense. Uninstalling the title/deleting it for good.

You could also ask the user to delete old versions when you install a new version to clean out the old data.

note: 
I have been using Game-List for years at this point which does this but it has been stagnating with its updates and bug fixes and Checker seems pretty great outside of the file management front.

**Comment by Willy-JL** [comment]
See FAQ. I’m sorry but gamelist is the main reason that brought me to make this, when files folders and paths get involved it gets too confusing for the user.

**Comment by CuddleBear92** [comment]
Thats sad to hear. But i disagree.
Everything with adding any data to checker right now feels so hands on and so manual. more hours lost managing this than compared to letting the software do the work.

**Comment by CuddleBear92** [comment]
even without an actual install feature, parsing the directory for the data could be done for bulk importing. but currently i dont see a way to specify the version you are installing. seems it just takes the current latest release and applies that to the install. so if you have old version installed then you cannot make that track correctly currently.

**Comment by Willy-JL** [comment]
> Atleast let me drag and drop the exe from explorer to the game thumbnail or the add exe button instead of manually navigating the explorer window you have or copy pasting the path.

If you read what’s on screen, you’d know you can do this. Any time a file picker is on screen, you can drop stuff into the window to select that.

**Comment by Willy-JL** [comment]
> even without an actual install feature, parsing the directory for the data could be done for bulk importing. but currently i dont see a way to specify the version you are installing. seems it just takes the current latest release and applies that to the install. so if you have old version installed then you cannot make that track correctly currently.

Again, first time setup thing. You make what version you had installed, then if an update come sit remember what you marked as installed. If you had it already outdated at install yes it’s not possible to tell it what you have installed, but then just update? And from the on it’s going to work fine

**Comment by CuddleBear92** [comment]
> If you read what’s on screen, you’d know you can do this. Any time a file picker is on screen, you can drop stuff into the window to select that.

Thanks for that, must have missed it. did skim through it, the UI doesnt indicate such a thing and the UI language does not dictate it either as it just seems like a custom UI for the normal explorer window and it feels like that.


> Again, first time setup thing. You make what version you had installed, then if an update come sit remember what you marked as installed. If you had it already outdated at install yes it’s not possible to tell it what you have installed, but then just update? And from the on it’s going to work fine

Easy to say when you have a huge backlog of titles and too little time to process it. GL manages this quite neatly with a window that tells you what version you are installing in a text field which is easy to edit.
But it was like i gathered from the start with how it works. A bit limiting. Also don't understand why there is a split with the mapped exe feature and the installed checkbox, shouldn't these be related and shouldn't the installed checkbox automatically be filled when you have an exe mapped? Seems like an oversight.

**Comment by Willy-JL** [comment]
> But it was like i gathered from the start with how it works. A bit limiting. Also don't understand why there is a split with the mapped exe feature and the installed checkbox, shouldn't these be related and shouldn't the installed checkbox automatically be filled when you have an exe mapped? Seems like an oversight.

It was linked in the past, but not everyone uses the tool like you do. The limiting this IS tying the 2 things together. You can stop steamrolling over others’ lawns when they’ve already worked at them for a long time and found a good compromise that works for them. You’re the only one complaining here.



> Thanks for that, must have missed it. did skim through it, the UI doesnt indicate such a thing and the UI language does not dictate it either as it just seems like a custom UI for the normal explorer window and it feels like that.

That’s because, as you probably noticed, the ui toolkit I’m using is very unusual, it’s not even a ui toolkit. Imgui draws the interfaces, but that’s it. To show them on screen I need another toolkit, in this case I use OpenGL and glfw. They don’t talk to each other that much, the only drag and drop feature is a callback when a file is dropped inside the window, no information as to where or on what widget. So how I do it is in gui.py, in MainGUI.drop_callback(). It checks the popup stack for the topmost file picker instance and applies the dropped file to the file picker’s selection
