### ISSUE TITLE
Add support for downloading and extracting files with real-debrid

### ISSUE THREAD

**Issue by dkir2021** [Willy-JL/F95Checker#58]
Likely a pipe dream feature request.

The idea is to help with downloads and managing the folders for each game the only extra bit required then would be to select the exe name and hit play.

There is a service called Real-Debrid which would let you unrestrict links if the user is premium for many of the paid services. So you could download stuff like the mega links via the application itself then in turn could let you also extract the archives into the exe default directory with the archive as the folder name, then set the exe path to that folder so when you select the exe on the game it just lists what's in the folder managed by the application.

API for real-debrid available here, probably only need the unrestrict link API as you can usually download directly from the produced link.
https://api.real-debrid.com/

**Comment by Willy-JL** [comment]
Read FAQ.

Also dont really see the need for real debrid in the first place... hosts are decently fast, and recently i added support for rpdl so now you have torrents right from the tool.

As for minimizing the steps on each update, why do you need to select exe each time? Its simple:
- make a folder with all your games, each game has its own folder, version IS NOT in the folder name (example: D:\Games\WVM) and select the exe ONCE
- on each update go to downloads tab, start a torrent (automatically opens in torrent app) or a regular download (you can setup jdownloader to listen for copying download links, so its automatic from f95checker to jdownloader)
- after download open game folder (middle click play button), delete files, move files from download
- done. press play. the exe is in same place.
