### ISSUE TITLE
Manual/customizable rpdl search

### ISSUE THREAD

**Issue by baloneysammich** [Willy-JL/F95Checker#60]
I've used the tool to grab a lot of torrents from rpdl, but for the first time it failed to yield [expected results](https://dl.rpdl.net/torrent/24107) for [Depraved Town: Remake](https://f95zone.to/threads/56935/). It was bound to happen eventually I guess. So it made we wonder if you could make it possible to customize the rpdl search, or even do completely manual searches:

1. In the **RPDL torrent search** dialogue, present a text entry field pre-filled with the failed query if no results are found so user can customize it.
2. Have the text entry field always present in the **RPDL torrent search** dialogue, just auto-initiate a search with the "default" query when the `🔍 Search` button is pressed. And whether or not a search yields results, always leave the query in the field.
3. Allow searching for rpdl torrents through the main interface text box by prefixing with `rpdl:` or such.

I realize this is a trivial "issue" (it's a feature request really) since we can just use the website. But I figured there's no harm in asking.

**Comment by Willy-JL** [comment]
Will look into it not finding the game, probably a trivial name conversion problem. And yes, a search bar would be very beneficial :)

As for invoking it from the main interface, that would need relocatingsome code, nothing too major. As of rhow to invoke it, your idea with the bottom bar does sound good, but we'll have to see what happens with the whole filter system (havent figured it out yet) so ill probably wait for that.

**Comment by baloneysammich** [comment]
> probably a trivial name conversion problem

In this case I'm guessing it's the weird torrent name "DepravedTown-0.3.0Remake" which unsurprisingly doesn't jive with the query "DepravedTownRemake".

> As for invoking it from the main interface, that would need relocating some code, nothing too major. As of how to invoke it ... we'll have to see what happens

Fact is, I've never felt the need to do a custom search from the tool so I wouldn't mind if it doesn't happen. But since it would presumably call up the same dialogue it seemed worth suggesting.

**Comment by Willy-JL** [comment]
Implemented via 173af7c79e8db4aa3a7610c90da32d31ee4d56b5, latest build includes it :D

Also included a note on the popup to donate to rpdl :smile:

**Comment by FaceCrap** [comment]
@baloneysammich despite the manual query being a fix, If you ever come across a failed search due to mismatch, let them know on their discord. Since they link back to the tool, any mismatch due to odd naming they'll fix almost instantly by renaming the torrent to match the query.

**Comment by Willy-JL** [comment]
Added in [10.1.2](https://github.com/Willy-JL/F95Checker/releases/tag/10.1.2)
