### ISSUE TITLE
Bug: KeyError: 'ai-cg'

### ISSUE THREAD

**Issue by ipaqi** [Willy-JL/F95Checker#61]
Bug just started occurring right now on refreshes.

![image](https://user-images.githubusercontent.com/4998016/216835548-658bb092-282b-4210-93d0-9e68a9572055.png)

Please advise

**Comment by Willy-JL** [comment]
Hm, looks like the forum added a new tag... will add it in a bit

**Comment by ipaqi** [comment]
@Willy-JL, before you fix it, there's an additional bug caused by this issue (missing tag option in your enum?) It's causing an error mid-parse so it's splitting up the update notification
![image](https://user-images.githubusercontent.com/4998016/218390199-7fa53c01-2192-4da9-923f-8c02f1b48d1e.png)
Also, if I try to use background mode, it looks like every parse generates this error. I left the checker on BG mode for 12 hours and when I came back I couldn't click my way through all the error notifications, I had to close the checker instead.

**Comment by ipaqi** [comment]
Maybe fix it but then locally revert and see if you can change the code so this doesn't happen or at least doesn't break up the notifications.

**Comment by Willy-JL** [comment]
Yes I also had that happen. It’s due to the new refresh process structure. It’s already in progress tracker

**Comment by Willy-JL** [comment]
Both bugs fixed in 42a56250f1b9ed72b40e1309839c73699f79f848 and 906671e860b359c0820cda7881fbbcdf95e717a6 respectively

**Comment by Willy-JL** [comment]
Fixed in [10.1.2](https://github.com/Willy-JL/F95Checker/releases/tag/10.1.2)
