### ISSUE TITLE
Tiny interface on 4k screen

### ISSUE THREAD

**Issue by Acrivec** [Willy-JL/F95Checker#62]
Hi, I'm using 4k screen with 150% scale and the app interface is just miniscule. 
![obraz](https://user-images.githubusercontent.com/26365504/219128470-bd66b720-609c-47e1-be2f-f7e5b887f63c.png)
If no full scaling options, then maybe at least allow for double/triple size of the interface (which should be very easy to code and would prevent scaling issues)?

**Comment by Willy-JL** [comment]
There in fact is a scaling setting in the sidebar

**Comment by Acrivec** [comment]
Oh I see now. I thought those things on right were a placeholders and would fill when clicking any of the added games, and not actual settings. Sorry.
