### ISSUE TITLE
Suggestion: Add count of matching games to kanban column header

### ISSUE THREAD

**Issue by FaceCrap** [Willy-JL/F95Checker#63]
As the subject says, in Kanban view, it would be nice if each column showed the count of matching games between parenthesis.

**Comment by Willy-JL** [comment]
Hm, good idea. Will put it in todo list

**Comment by Willy-JL** [comment]
Fixed in [10.1.2](https://github.com/Willy-JL/F95Checker/releases/tag/10.1.2)
