### ISSUE TITLE
Backup, export and import from json/csv

### ISSUE THREAD

**Issue by Whatthee** [Willy-JL/F95Checker#64]
I would like a function to backup the table as a .csv or .json file so that I can backup the list manually if I reinstall f95checker and perhaps edit it in Excel. It could just be a list of Thread links, Ratings, Labels and Notes. Perhaps also added on, last played date and played/installed.

**Comment by Willy-JL** [comment]
Mfw db.sqlite3

The main application database is basically what you are asking for... use that... you can use sqlite browser to open it and edit it, or you can just copy the file and paste it across pcs

**Comment by Whatthee** [comment]
Thank you, great work by the way :)
