### ISSUE TITLE
Refresh opens up separate windows for each updated game

### ISSUE THREAD

**Issue by Whatthee** [Willy-JL/F95Checker#65]
Since the last update, I've had some trouble with all the updates popping up in separate windows. When I have +10 games updated on a refresh this can be a bit frustrating including multiple ai-cg errors.

**Comment by Willy-JL** [comment]
Am aware. Issue is the refresh continues after an error occurs, so further updated games get their own popup

**Comment by Whatthee** [comment]
I see, thank you for the quick reply

**Comment by Willy-JL** [comment]
Fixed in [10.1.2](https://github.com/Willy-JL/F95Checker/releases/tag/10.1.2)
