### ISSUE TITLE
"Recently Updated" handling

### ISSUE THREAD

**Issue by baloneysammich** [Willy-JL/F95Checker#67]
With a lot of games the "Recently Updated" icon can be a bit of an annoyance. I'm tracking a lot of games and frankly most of them I don't play regularly. This makes the "Recently Updated" status a bit of an annoyance. It would be nice if there were a way to bulk clear the icon.

It would be **super nice** if it clearing it could be automated in some way. Such as auto clearing the icon for games that were "tagged" a certain time ago or a certain number of refreshes ago. Granted I only update manually so I'm sure this would get complicated in the context of auto-refreshing. It would be **super duper nice** if one could manually mark games that _wouldn't_ be auto-cleared in this way.

I realize the "super plus" requests may be a lot to ask, so no need to explain if they're not practical or NRTYI.

**Comment by Willy-JL** [comment]
Maybe you could archive those games? Idk

what I do is that I sort my list based on installed and secondarily by played, so I see updates only if it’s for games I have installed, and they appear at the top of the list, others get the icon but it’s lower in the list

**Comment by baloneysammich** [comment]
I guess if I decide that I can't deal with it any more I could figure out how to use sql commands to modify the db directly. Feel free to close this if you don't intend to consider it. Thanks for the input regardless. :)

**Comment by baloneysammich** [comment]
FWIW I accidentally found a practical way to clear the icon on a bunch of games quickly. Basically, use filters to show only games that have the icon then just rapid middle-click at the top of the list. Cleared dozens in a matter of seconds.

**Comment by Willy-JL** [comment]
yeah i cant really think of a practical way to improve this behavior... what youre doing now is what i do too lol
