### ISSUE TITLE
App showing "Thread parsing error" on refresh for thread 133108

### ISSUE THREAD

**Issue by kenneththerodgers** [Willy-JL/F95Checker#68]
**App version**: 10.1.1

**OS**: 
Edition	Windows 11 Home
Version	22H2
Installed on	‎10-‎Feb-‎23
OS build	22621.1194
Experience	Windows Feature Experience Pack 1000.22638.1000.0

**Steps to reproduce**:
1. Add thread [133108](https://f95zone.to/threads/of-devotion-and-despondence-v0-1-12-earliestbird.133108/) to the app.
2. Hit refresh.

**Error screenshot**:
![image](https://user-images.githubusercontent.com/74833875/222879631-015e9f52-0193-4484-92c5-ca4b9975e1a8.png)

**Logs**:
```
Traceback (most recent call last):
  File "D:\a\F95Checker\F95Checker\modules\parser.py", line 303, in thread
  File "C:\hostedtoolcache\windows\Python\3.11.1\x64\Lib\enum.py", line 793, in __getitem__
KeyError: 'ai-cg'
```

**Comment by Willy-JL** [comment]
Known issue, fixed on main branch, release soon
