### ISSUE TITLE
Titles and Status broken

### ISSUE THREAD

**Issue by ipaqi** [Willy-JL/F95Checker#69]
Something must have changed in f95zone, because the titles you're generating now include the prefixes in the title text

![image](https://user-images.githubusercontent.com/4998016/229284596-25c1ab9f-89a4-4e3e-b5ce-2acd9483da0f.png)

Also, Completed status gets reset to Normal, probably the same for OnHold, etc.

Might be a good time to split up the update dialog between version updates and other info updates. I just got 100 updates and none of them were for a new version.

**Comment by ipaqi** [comment]
Fixed it on my own machine. fix is in parser.py:

line 53:
![image](https://user-images.githubusercontent.com/4998016/229290892-3f6fb461-8472-48b2-b3ce-3862b51ab90f.png)

line 170:
![image](https://user-images.githubusercontent.com/4998016/229290934-d92694f0-9354-4996-b110-0fd80faddecc.png)

This change on f95z's side pretty much breaks usablilty for the update dialog.

I recommend you commit these changes and get out a release version as a hotfix instead of waiting for more features to complete

**Comment by yohudood** [comment]
i have the same problem

**Comment by baloneysammich** [comment]
Respect for providing a fix, but screenshots of text... I threw up in my mouth a little bit when I saw that. XD

**Comment by ipaqi** [comment]
> Respect for providing a fix, but screenshots of text... I threw up in my mouth a little bit when I saw that. XD

On the one hand, fair.

On the other hand, there is no actual better way to show the change since Willy doesn't allow people to make pull requests

**Comment by Willy-JL** [comment]
> On the other hand, there is no actual better way to show the change since Willy doesn't allow people to make pull requests

??????????

**Comment by ipaqi** [comment]
> > On the other hand, there is no actual better way to show the change since Willy doesn't allow people to make pull requests
> 
> ??????????

I tried to make a pull request from Visual Studio Code to make this easier and it told me I didn't have permission or whatever.

I assumed that's how the repo is set up (which I believe is the default in GitHub anyway).

If I should be able to make pull requests if I have a contribution, I apologize for assuming otherwise, but also how do I do that?

**Comment by Willy-JL** [comment]
From the pull requests tab... on GitHub... if vscode tells you that you dont have permission, then thats somethign setup incorrectly with your vscode. What I assume happened is that you cloned the repo as-is and made changes to your local copy. In that case, the "you cont have permission" is because it is trying to push changes directly to my repo. What you do is that you fork the repo, clone that, make changes there, then make a pull request into my repo.

**Comment by Willy-JL** [comment]
Anyway, this is now fixed via 5e159c8e155b3ad0ce6cabd9b9937e5a3e5264cb and 6c643d1f699cd667fb21d4407e8896bf189ae7ea, thanks for the easy solution @ipaqi. Release is incoming

**Comment by Willy-JL** [comment]
Fixed in [10.1.2](https://github.com/Willy-JL/F95Checker/releases/tag/10.1.2)
