### ISSUE TITLE
Add games by importing text files with game names.

### ISSUE THREAD

**Issue by prokerr** [Willy-JL/F95Checker#73]
![image](https://user-images.githubusercontent.com/129399918/230539677-8f6e526e-50c8-41a1-be0c-136838df470e.png)
An option to import this .txt file, check the name of the games and add them to the checker? Possible to add?

**Comment by FaceCrap** [comment]
Currently not possible and I doubt it ever will be. There are too many possibilities for wrong matches as there exist games that have the same name. So your best option would be to get the links for these games. Even if there are other games with the same name, the link would identify it uniquely. Or use one of the other import options (bookmarked, watched or physical url shortcut)

**Comment by CrocodileDuty** [comment]
> physical url shortcut

Hey what is this shortcut that you mentioned?
