### ISSUE TITLE
Allow setting Last Updated for custom games

### ISSUE THREAD

**Issue by baloneysammich** [Willy-JL/F95Checker#75]
### Feature Request

Please allow manually setting the **Last Updated** value for custom added games. Even if it's stored in Unix time or something in the db and we have to input it as such.

I usually sort by Last Updated and would rather Custom games not be relegated to the bottom.

Thanks.

**Comment by FaceCrap** [comment]
@baloneysammich I suggested in the forum thread to have the Last Update field automatically filled when ticking the Updated  he k ox in the info screen. A minor disadvantage is that there may be one or more days difference between the auto-filled date and the date the thread got updated, but it saves us the trouble of entering it manually.
