### ISSUE TITLE
Fix refresh cancel bug

### ISSUE THREAD

**Issue by baloneysammich** [Willy-JL/F95Checker#77]
I cancelled a Refresh with a bunch of full rechecks pending. When I started it again (no program restart) the total number of full rechecks was greater than the number of games I track.

I guess the variable didn't get reset to zero.

Refresh completed normally, only consequence was UI still showed "Running ## full rechecks" at bottom right after refresh completed.

**Comment by FaceCrap** [comment]
can confirm this...
![image](https://github.com/Willy-JL/F95Checker/assets/95778718/31635145-dbfa-450e-99eb-0d1ea6c65df9)
