### ISSUE TITLE
Remove F95's redirect page from Download URLs

### ISSUE THREAD

**Issue by gimpyestrada** [Willy-JL/F95Checker#78]
Would it be possible for you to remove the redirection junk that F95 adds around some download URLs?

I know they do it with Mega and Pixeldrain and Workupload.

I'm not sure if this is feasible or not.

It would allows us to click the download link directly from your app and we wouldn't have to hit f95 at all for downloads.

**Comment by Willy-JL** [comment]
hover over the question mark next to "regular downloads".
basically a middle click will autocomplete the captcha then copy the link
a left click opens the link in browser. if you select the embedded browser, then it will bypass the captcha and remain open in the embedded browser

**Comment by gimpyestrada** [comment]
> d

Could the middle click on masked open it in the browser instead of copying?

**Comment by Willy-JL** [comment]
No, the idea is that you use a download manager and make it watch for links in clipboard. My suggestion is jdownloader2. There is no reason to use the browser, downloading in browser is retarded and dogshit for files over 50 megabytes

**Comment by gimpyestrada** [comment]
You could make a right click open in a browser maybe?  I don't have any problem with downloading in my browser.  Plus mostly I click Mega links and those are downloaded by the mega app anyway.
