### ISSUE TITLE
Can't Refresh Games - Two-Step Authy Error

### ISSUE THREAD

**Issue by trolly056** [Willy-JL/F95Checker#84]
Tried to refresh and got this error
![F95Checker_TFRDX5miUa](https://github.com/Willy-JL/F95Checker/assets/8355453/03928ce6-f093-4815-8616-5b0eb6cf0845)
Noticed the "two-step?" part of the url and realized it's the two-step authentication that expires every 30 DAYS, struggled and panicked cuz i couldn't find a login button nor remember how i logged in the first time i downloaded the app, remembered there was a INTEGRADED browser mode 
![F95Checker_EHa88bPrYX](https://github.com/Willy-JL/F95Checker/assets/8355453/95395b6c-be9b-42f8-8a30-f06ffd3f7b49) 
clicked a game thread
![F95Checker_g1ZVXDED1S](https://github.com/Willy-JL/F95Checker/assets/8355453/0a65bfd5-5dae-4554-aa27-5e0d80112531)
entered my authy-codes, however the moment i press CONFIRM
![F95Checker_PNt3nKMvqd](https://github.com/Willy-JL/F95Checker/assets/8355453/6a06cbe8-ce42-4fb6-bfc2-65555d20b201)
it simply refreshes the page, took me a little while till i got the thought that maybe my stored login with username and password or bugged or something, so i decided to do a full login by clicking on LOGIN on the top right of the integrated browser and this time it worked, i can use the forums and browser the game threads, use last updates page and everything, however the moment the browser closes i lose the session and the tool cannot refresh my games and gives me that two-step error again and i have to login again, curiously i tried to refresh the games with the integrated browser open and it still gives the same error, before i thought it was connected now i'm not sure anymore and i can still use the integrated browser though refresh error gives me the two-step auth error and till i close the integrated browser screen i don't lose the session.
I don't know how to fix this, i didn't change any settings and i have been using F95Checker for a long time. Yesterday was working just fine. I'm typing this as i just woke up and did the morning refresh then got this error. Doesn't seem to be a account thing cuz my normal browser session works just fine. If i missed anything let me know. win10, my normal browser is google chrome.

**Comment by Willy-JL** [comment]
You just had a X Y problem moment. 2fa is handled correctly in f95checker, it will ask to login again / refresh the 2fa if it is expired. The issue here is that the cookies because too much for the server to handle. Simply click Manage > Clear > All Cookies.
