### ISSUE TITLE
Fix searches with "&" in RPDL

### ISSUE THREAD

**Issue by FaceCrap** [Willy-JL/F95Checker#91]
rpdl.net has gotten into the habit of converting "&" in thread titles to "And" instead of dropping them from the torrent name.
As a result you need to switch to a manual search. In itself not an issue, but may stump inexperienced users, who aren't aware why it happens.
So to accommodate for those situations, it would be nice if F95Checker did the same thing, so these users aren't tempted to post this as a possible problem.

I haven't encountered other situations with non-alphabetic characters, yet. Honestly don't think there's other non-alpha characters with a word equivalent existing in thread titles.

**Comment by Willy-JL** [comment]
also made it consider digits, i saw that they do include those
