### ISSUE TITLE
Right-click on a thread had an option for checker

### ISSUE THREAD

**Issue by ogkimra** [Willy-JL/F95Checker#92]
Previously we could add a thread by right clicking on the website (with extension installed)? But I dont see that option anymore? 
Is it removed or is it firefox bug?

**Comment by FaceCrap** [comment]
Still has, at least in my Firefox 117.0.1 it has...
![image](https://github.com/Willy-JL/F95Checker/assets/95778718/6927dbf4-056c-470f-badd-6977d13de8db)

**Comment by littleraisins** [comment]
I've had this issue with Firefox too, it's most likely a Firefox bug

**Comment by FaceCrap** [comment]
Which version of FF? Normal or ESR?

**Comment by Willy-JL** [comment]
I can say that for me too it would randomly disappear. Try reinstalling the extension
